# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20190328_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
