# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20190328_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
